#!/usr/bin/env python3
"""
CLI: Generate a standalone report for a CSV + strategy.
Paper-only. No broker calls.
"""
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import argparse

from market_data.csv_validator import validate_csv
from strategy_runtime.csv_strategy_runner import run_strategy_on_csv


def main():
    parser = argparse.ArgumentParser(description="Generate CSV strategy report.")
    parser.add_argument("--csv", required=True, help="Path to CSV file")
    parser.add_argument("--strategy", required=True, help="Strategy name")
    parser.add_argument("--symbol", default=None, help="Symbol override")
    parser.add_argument("--timeframe", default=None, help="Timeframe override")
    parser.add_argument("--output", default="reports/csv_workflow/report.md", help="Report output path")
    args = parser.parse_args()

    print("PAPER-ONLY / DATA-ONLY. No live trading. No order submission.")

    validation = validate_csv(args.csv, symbol=args.symbol, timeframe=args.timeframe)
    strategy_result = run_strategy_on_csv(
        args.csv, args.strategy,
        symbol=args.symbol, timeframe=args.timeframe, validate=False,
    )

    lines = [
        "# CSV Strategy Report",
        "",
        "> **PAPER-ONLY / DATA-ONLY. No live trading. No order submission.**",
        "",
        "## Data Source",
        f"- CSV file: `{args.csv}`",
        f"- Symbol: {validation['inferred_symbol']}",
        f"- Timeframe: {validation['inferred_timeframe']}",
        f"- Source: {validation['inferred_source']}",
        f"- First timestamp: {validation['first_timestamp']}",
        f"- Last timestamp: {validation['last_timestamp']}",
        f"- Row count: {validation['row_count']}",
        "",
        "## Validation",
        f"- Valid: {validation['valid']}",
    ]
    if validation['errors']:
        lines.append("### Errors")
        for e in validation['errors']:
            lines.append(f"- {e}")
    if validation['warnings']:
        lines.append("### Warnings")
        for w in validation['warnings']:
            lines.append(f"- {w}")
    lines.append("")
    lines.append(f"## Strategy: {args.strategy}")
    sig = strategy_result.get("latest_signal")
    if sig:
        lines.append(f"- **Direction:** {sig['direction']}")
        lines.append(f"- **Weight:** {sig.get('weight')}")
        lines.append(f"- **Timestamp:** {sig['timestamp']}")
    else:
        lines.append("- No signal generated.")
    lines.append("")
    lines.append("---")
    lines.append("Generated by Quant_Agent Phase 12 -- CSV Report Generator")

    out_path = __import__('pathlib').Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Report saved to {out_path}")


if __name__ == "__main__":
    main()
